line-length = 88
lint.ignore = [
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    "D106",  # Missing docstring in public nested class
    "D107",  # Missing docstring in __init__
    "D203",  # 1 blank line required before class docstring
    "D212",  # Multi-line docstring summary should start at the first line
    "D213",  # Multi-line docstring summary should start at the second line
    "D404",  # First word of the docstring should not be "This"
    "D405",  # Section name should be properly capitalized
    "D406",  # Section name should end with a newline
    "D407",  # Missing dashed underline after section
    "D410",  # Missing blank line after section
    "D411",  # Missing blank line before section
    "D412",  # No blank lines allowed between a section header and its content
    "D416",  # Section name should end with a colon
    "D417",
    "D417",  # Missing argument description in the docstring
]
lint.select = [
    "A",  # flake8 builtins
    "C9", # mcabe
    "D",  # pydocstyle
    "E",  # pycodestyle (errors)
    "F",  # Pyflakes
    "I",  # isort
    "S",  # flake8-bandit
    "T2", # flake8-print
    "W",  # pycodestype (warnings)
]

[lint.isort]
combine-as-imports = true

[lint.mccabe]
max-complexity = 8

[lint.per-file-ignores]
"*tests/*" = [
    "D205",  # 1 blank line required between summary line and description
    "D400",  # First line should end with a period
    "D401",  # First line should be in imperative mood
    "D415",  # First line should end with a period, question mark, or exclamation point
    "E501",  # Line too long
    "E731",  # Do not assign a lambda expression, use a def
    "S101",  # Use of assert detected
    "S105",  # Possible hardcoded password
    "S106",  # Possible hardcoded password
    "S113",  # Probable use of requests call with timeout set to {value}
]
"*/migrations/*" = [
    "E501",  # Line too long
]
"*/settings.py" = [
    "F403",  # from {name} import * used; unable to detect undefined names
    "F405",  # {name} may be undefined, or defined from star imports:
]
"*/settings/*" = [
    "F403",  # from {name} import * used; unable to detect undefined names
    "F405",  # {name} may be undefined, or defined from star imports:
]
